server:
  port: 8189
  servlet:
    context-path: /market
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/geekmarket?serverTimezone=Europe/Moscow
    username: root
    password: BzBpmbrt
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect